# NUMPY

#### Numpy stands for numerical python
Using numpy we can perform :-
1.Mathematical and logical calcualtions on an array <br>
2.fourier transform and routeins for shape manipulation <br>
3.It has built in functions for linear algebra random number generation <br>
4.Used for scientific calculation <br>
5.It is faster than python list <br>
6.It is fast because it is associated with C programming <br>

#### shortcuts
esc+ 2 times d = delete a cell <br>
esc + b = insert cell below <br>
esc + a = insert cell above <br>
esc + [1 to 6] = headings <br>

In [1]:
import numpy as np; # importing numpy library

In [2]:
a=[1,2,3,4];
myarr=np.array(a); # for creating an array;
myarr


array([1, 2, 3, 4])

In [3]:
# or 
myarr=np.array([1,2,3,4]);
myarr

array([1, 2, 3, 4])

In [4]:
# taking input from user

a=[]
n=int(input('enter the size of the array'));
for i in range(n):
    val=int(input('enter number'));
    a.append(val);
myarr=np.array(a);
myarr
    

enter the size of the array3
enter number1
enter number2
enter number3


array([1, 2, 3])

In [5]:
# creating 2D array 
a=[[1,2,3],[4,5,6],[7,8,9]];
myarr=np.array(a);
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# or
myarr=np.array([[1,2,3],[4,5,6],[7,8,9]]);
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#or taking input from user
a=[]
row=int(input('enter the no of rows of the array'));
col=int(input('enter the no of columns of the array'));

for i in range(row):
    b=[];
    for j in range(col):
        val=int(input('enter number :'));
        b.append(val);
    a.append(b);
myarr=np.array(a);
myarr
        

enter the no of rows of the array3
enter the no of columns of the array3
enter number :1
enter number :2
enter number :3
enter number :4
enter number :5
enter number :6
enter number :7
enter number :8
enter number :9


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print("the dimension of array = ",myarr.ndim); # printing dimension of the array
print("the shape of the array is = ",myarr.shape) # printing shape of the array

the dimension of array =  2
the shape of the array is =  (3, 3)


## Numpy Functions

In [9]:
# 1. Zeroes :- creates an array (either one or multi-dimensional) and fill all the values with zero

# a.one dimensional
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [10]:
# b.2 dimensional
arr=np.zeros([2,3]) # in square brackets the dimension of the array
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# 2. Ones :- creates an array and fill all the values with one(1)

# a.one dimensional
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [12]:
# b.2 dimensional
arr=np.ones([3,4]);
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# 3.eye :- creates an array with all diagonal elements as 1 and rest as 0 (in a square matrix).
#In case of non-square matrix the values are still 1 for diagonal (upto which it can draw diagonal) and rest are zero. for eg,

# a. square matrix
arr=np.eye(5);
print(arr);

print();
# b. non-square matrix
arr=np.eye(3,4)
print(arr);

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [14]:
# 4. diag :- creates a 2 dimensional array with all diagonal elements as given value and rest other as zero (in a square matrix);

arr=np.diag([2,3,4,5]);
arr

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [15]:
# to get diagonal elements from a 2 dimensional array
print(np.diag(arr));

[2 3 4 5]


In [16]:
# 5. randint :- generate a random number between a given range
# the syntax is rand(min,max,total_values);
# value changes every time we run the program

arr=np.random.randint(1,10,3);
arr

array([6, 1, 1])

In [17]:
# 5. rand :- generate a random value between 0 to 1.
# Syntax :- rand(number_of_values);

arr=np.random.rand(3);
arr

array([0.16351226, 0.15094205, 0.39910884])

In [18]:
# generating 2 dimensional array using rand function
arr=np.random.rand(2,3);
arr

array([[0.98218974, 0.94237555, 0.07340011],
       [0.1076138 , 0.02950896, 0.90957025]])

In [19]:
# 7. randn :- generates a random close to zero(0) . This may return +ve or -ve values as well
#syntax :- randn(number_of_values);

arr=np.random.randn(4);
arr

array([0.05960896, 0.80679737, 0.64884973, 0.96550216])

In [20]:
# 8. identity :- genenrates an identity matrix of specified order
arr=np.identity(4);
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
# 9. repeat :- repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0);
r1


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### One dimensional array

In [22]:
# Indexing
# it supports indexing from left to right as well as from right to left
# when left to right indexing starts from 0.
# while right to left indexing starts from -1
# this indexing technique is much similar to indexing technique of lists

In [24]:
a=[]
size=int(input('enter the size of the array'));
for i in range(size):
    val=int(input('enter number'));
    a.append(val);
myarr=np.array(a);

for i in range(myarr.size):
    print("element at index ",i," is ",myarr[i]);
    

enter the size of the array4
enter number1
enter number2
enter number3
enter number4
element at index  0  is  1
element at index  1  is  2
element at index  2  is  3
element at index  3  is  4


In [25]:
# Slicing
myarr=np.array([1,2,3,4,5,6]);
print(myarr[2:4]); # array(starting_value:end_value-1);



[3 4]


In [26]:
print(myarr[2:]); # from 2 till end
print(myarr[:2]) # from 0 til 2-1 i.e 1

[3 4 5 6]
[1 2]


In [27]:
# accessing last index using -ve indexing
print(myarr[-2:]) # from 2nd last till end
print(myarr[1:-1]) 

[5 6]
[2 3 4 5]


### Reshaping Data 

In [28]:
arr=np.random.randint(1,100,12);
print(arr); # printing array
print(arr.shape) # printing shape of the array


[39 19 80 92 46 71 33 94 15 82 97 91]
(12,)


In [29]:
# reshaping one dimensional array to 2 dimensional
arr=arr.reshape(3,4); # only provide that combination of dimension whose product equals to actual size of the array i.e 12
print(arr);

[[39 19 80 92]
 [46 71 33 94]
 [15 82 97 91]]


In [30]:
# converting to 3 dimensional array
arr=arr.reshape(2,2,3);
arr

array([[[39, 19, 80],
        [92, 46, 71]],

       [[33, 94, 15],
        [82, 97, 91]]])

In [31]:
# again converting this 3D array to 1D
arr=arr.reshape(12);
arr

array([39, 19, 80, 92, 46, 71, 33, 94, 15, 82, 97, 91])

In [32]:
# what if we don't provide no of rows or columns during reshaping our array
# e.g

arr=arr.reshape(2,-1) 
print(arr,"\n")

# or

arr=arr.reshape(-1,2);
print(arr);

# any way can be used for this as -1 entry wll be calculated by the system


[[39 19 80 92 46 71]
 [33 94 15 82 97 91]] 

[[39 19]
 [80 92]
 [46 71]
 [33 94]
 [15 82]
 [97 91]]


In [33]:
# Seed Function :- generates fix set of random number in given range
np.random.seed(12);
arr=np.random.randint(1,100,12);
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50, 53,  6])

### Two dimensional Array

In [34]:
# Indexing/Slicing of two dimensional array may be done by two ways:
# 1. Indexing/Slicing using double bracket notation
# 2. Indexing/Slicing using single bracket notation

In [35]:
#Creation
a=[]
row=int(input('enter the no of rows of the array'));
col=int(input('enter the no of columns of the array'));

for i in range(row):
    b=[];
    for j in range(col):
        val=int(input('enter number :'));
        b.append(val);
    a.append(b);

#Printing
for i in range(row):
    for j in range(col):
           print(a[i][j],end=" ");
    print();

enter the no of rows of the array3
enter the no of columns of the array3
enter number :1
enter number :2
enter number :3
enter number :4
enter number :5
enter number :6
enter number :7
enter number :8
enter number :9
1 2 3 
4 5 6 
7 8 9 


In [36]:
# Slicing
# Single bracket notation
# syntax : array[row range,col range] --> here col range=col range-1
a[:2] # from 0th row to 1st row

[[1, 2, 3], [4, 5, 6]]

In [37]:
print(a[1:5])

[[4, 5, 6], [7, 8, 9]]


In [38]:
a[2:] # last row

[[7, 8, 9]]

### View vs Copy

In [39]:
# e.g View technique
a=np.array([10,20,30,40,50,60,70,80]);
slicing=a[3:6]
print(slicing)
slicing[:]=0
print(a) # original array got upadated

[40 50 60]
[10 20 30  0  0  0 70 80]


In [40]:
# e.g copy technique
a=np.array([10,20,30,40,50,60,70,80]);
slicing=a[3:6].copy()
print(slicing)
slicing[:]=0
print(a) # original array not updated

[40 50 60]
[10 20 30 40 50 60 70 80]


#### Conditional Selection

In [41]:
arr=np.arange(1,16) # creates an array in range 1 to 15
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
arr>10 # returns true if element is greater than 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [43]:
b=arr>10
arr[b] # stores value greater than 10

array([11, 12, 13, 14, 15])

In [44]:
arr[arr<5] # print elements less than 5 in the array

array([1, 2, 3, 4])

In [45]:
arr[arr%2==0] # print even elements


array([ 2,  4,  6,  8, 10, 12, 14])

In [46]:
# updating values 
arr[arr%2==0]=0 # replace even elements with zero
arr

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15])

####  Operations on numpy array

In [47]:
arr=np.arange(1,5)
arr

array([1, 2, 3, 4])

In [48]:
arr*2 # multiply each element with 2

array([2, 4, 6, 8])

In [49]:
arr+2 # add every element with 2


array([3, 4, 5, 6])

In [50]:
arr**2 # square of each element

array([ 1,  4,  9, 16], dtype=int32)

In [51]:
# in numpy array divide by zero gives infinity, not an error

In [52]:
arr1=np.arange(5,9)
arr1

array([5, 6, 7, 8])

In [53]:
arr + arr1 # sum of arr and arr1

array([ 6,  8, 10, 12])

#### Operation on 2 D array

In [54]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)

In [55]:
a

array([[1, 2],
       [3, 4]])

In [56]:
b

array([[5, 6],
       [7, 8]])

In [57]:
a+b

array([[ 6,  8],
       [10, 12]])

In [58]:
a*b

array([[ 5, 12],
       [21, 32]])

In [59]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [60]:
a.dot(b) # this will give proper matrix multiplication result

array([[19, 22],
       [43, 50]])

In [61]:
a**b # a exponent b

array([[    1,    64],
       [ 2187, 65536]], dtype=int32)

#### Some more Functions

In [62]:
arr=np.array([10,20,30,40,50,60])
arr

array([10, 20, 30, 40, 50, 60])

In [63]:
np.min(arr) # returns min value 

10

In [64]:
np.max(arr) # returns max value

60

In [65]:
np.argmin(arr) # returns index of min value

0

In [66]:
np.argmax(arr) # returns index of max value

5

In [67]:
np.sqrt(arr) # square root of every number

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])

In [68]:
np.sin(arr) # sin value of every number

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485,
       -0.30481062])

In [69]:
np.cos(arr) # cos value of every number

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603,
       -0.95241298])

In [70]:
# linspace function :- returns value between a given range and with a same gap between consecutive elements

print(np.linspace(1,2,5)); # (min_value, max_value, number_of_values)

[1.   1.25 1.5  1.75 2.  ]


In [71]:
# on 2D arrays
np.random.seed(122)
matrix=np.random.randint(1,21,9).reshape(3,3)
matrix

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [72]:
# np.sum(matrix) or
matrix.sum()

116

In [73]:
np.min(matrix)

3

In [74]:
np.max(matrix)

17

In [75]:
# finding row wise and column wise min or max

# axis=1 --> for row
#finding row wise min value
np.min(matrix,axis=1) 

array([11, 13,  3])

In [76]:
# finding col wise min value
np.min(matrix,axis=0)

array([ 3, 11, 11])

In [77]:
# finding row and column wise max value
np.max(matrix,axis=1)

array([16, 17, 16])

In [78]:
np.max(matrix,axis=0)

array([17, 16, 16])

In [79]:
np.cumsum(matrix) # returns cumulative sum of the matrix

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116], dtype=int32)

In [80]:
np.random.seed(122)
arr=np.random.randint(1,21,10)
arr

array([16, 11, 13, 17, 13, 16,  3, 16, 11, 10])

In [81]:
b=np.random.shuffle(arr) # shuffle the array elements --> changing the position of array elements
print(b)

None


In [82]:
np.unique(arr) # returns unique elements from the array

array([ 3, 10, 11, 13, 16, 17])

In [83]:
# counting unique number in the array
np.unique(arr).size

6

In [84]:
print(np.unique(arr,return_index=True,return_counts=True));
# returns three arrays
# The array with unique values
# The array with respective index values
# The array with counting of frequency

(array([ 3, 10, 11, 13, 16, 17]), array([9, 5, 3, 0, 1, 8], dtype=int64), array([1, 1, 2, 2, 3, 1], dtype=int64))


### Vertical and Horizontal Stacking

In [85]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a,b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [86]:
np.hstack((a,b)) # horizontally arranges the arrays

array([1, 2, 3, 4, 5, 6, 7, 8])

In [87]:
np.vstack((a,b)) # vertically arranges the array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [89]:
np.hstack((a,b)) # horizontally arranges the matrix


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [90]:
np.vstack((a,b)) # vertically arranges the matrix


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### Searching an Element in numpy array

In [91]:
arr=np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [92]:
x=np.where(arr==4) # returns the index of 4
print(x) 

(array([3], dtype=int64),)


In [93]:
result=np.where(arr%2==0)
print(result) # returns array of index of even elements

(array([1, 3], dtype=int64),)


In [94]:
#this method performs a binary search in the array and returns the index 
#where the speicfied value would be inserted to maintain the search order
x=np.searchsorted(arr,7)
print(x)

5


In [95]:
# by default searching is performed from left side of the array, for performing form right side
x=np.searchsorted(arr,7,'right')
print(x)

5


## NUMPY  Questions

##### 1. Write a statement to import numpy

In [96]:
# Ans.
import numpy as np

##### 2. Creating an array using numpy?

In [97]:
#Ans
array=np.array([1,2,3,4])
array

array([1, 2, 3, 4])

##### 3.Create an array of 10 random integers?

In [98]:
#Ans
arr=np.random.randint(1,10,5)
arr

array([2, 7, 7, 1, 6])

##### 4.Create an array of elements from 10-20

In [99]:
#Ans
arr=np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

##### 5.Create an array which contains value 5, 10 times

In [100]:
arr=np.ones(10)*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

##### 6.Create a one dimensional array and convet that into 3*3 matrix

In [101]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### 7.Create an array and then convert all the even numbers with 0

In [102]:
#Ans.
arr=np.arange(1,11);
arr[arr%2==0]=0
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

##### 8. Create a 2D array of size 3*3 but all the elements should be between 0 and 1

In [103]:
# Ans.
arr=np.random.rand(9).reshape(3,3)
arr

array([[0.53665674, 0.67515235, 0.41526399],
       [0.37040662, 0.72482967, 0.34418396],
       [0.52770975, 0.87016427, 0.77298345]])

##### 9. Concatenate 2D array horizontally and vertically

In [104]:
arr1=np.arange(1,5).reshape(2,2)
arr2=np.arange(5,9).reshape(2,2)

np.hstack((arr1,arr2)),np.vstack((arr1,arr2))

(array([[1, 2, 5, 6],
        [3, 4, 7, 8]]),
 array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]))